# -*- coding: utf-8 -*-
"""Leela-Sidhik-V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GPfmdfGPkW6NSebtea32vQuhsTqNIEfG
"""

# Final Swin-Small notebook (copy-paste into one Colab cell)
# Preconditions: upload kaggle.json to Colab (left Files pane) BEFORE running.

# ----------------- 0) Install specific working packages -----------------
import subprocess, sys, os, time, math, random
def pip_install(pkgs):
    subprocess.run([sys.executable, "-m", "pip", "install", "--upgrade"] + pkgs, check=True)

# Install known-good versions (avoid reinstalling torch to prevent conflicts)
try:
    pip_install(["timm==0.9.2", "albumentations==1.4.0", "grad-cam==1.4.6", "focal-loss", "kaggle", "scikit-learn", "matplotlib", "seaborn"])
except Exception as e:
    print("Package install warning (continuing):", e)

# ----------------- 1) Kaggle setup & dataset download -----------------
if os.path.exists("/content/kaggle.json"):
    os.makedirs("/root/.kaggle", exist_ok=True)
    subprocess.run(["cp", "/content/kaggle.json", "/root/.kaggle/kaggle.json"], check=False)
    subprocess.run(["chmod", "600", "/root/.kaggle/kaggle.json"], check=False)
else:
    print("Upload kaggle.json to Colab (Files pane) then re-run this cell.")

if not os.path.exists("/content/chest_xray"):
    try:
        subprocess.run(["kaggle", "datasets", "download", "-d", "paultimothymooney/chest-xray-pneumonia", "-p", "/content", "--unzip"], check=True)
        print("Dataset downloaded.")
    except Exception as e:
        print("Kaggle download failed:", e)

# ----------------- 2) Imports & safe module fallbacks -----------------
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
import torch, torch.nn as nn, torch.optim as optim
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
import timm
import albumentations as A
from albumentations.pytorch import ToTensorV2
from sklearn.metrics import confusion_matrix, roc_auc_score, roc_curve, classification_report, accuracy_score
from tqdm.notebook import tqdm
print("Imports OK.")

# grad-cam import (installed above)
try:
    from grad_cam import GradCAM
    from grad_cam.utils.image import show_cam_on_image
    from grad_cam.utils.model_targets import ClassifierOutputTarget
    print("grad-cam imported.")
except Exception as e:
    print("grad-cam import failed:", e)
    GradCAM = None

# focal loss import fallback
FocalLoss = None
try:
    # try common exposed module names
    try:
        from focalloss import FocalLoss as FocalLoss_mod
        FocalLoss = FocalLoss_mod
    except Exception:
        from focal_loss.focal_loss import FocalLoss as FocalLoss_mod2
        FocalLoss = FocalLoss_mod2
    print("FocalLoss available.")
except Exception as e:
    print("FocalLoss not available; will use weighted CrossEntropy.", e)
    FocalLoss = None

# ----------------- 3) Config & hyperparameters -----------------
DATA_DIR = Path("/content/chest_xray")
FIG_DIR = Path("/content/paper_figures"); FIG_DIR.mkdir(exist_ok=True)
IMG_SIZE = 224
BATCH_SIZE = 16   # try 16; lower to 8 if OOM
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
SEED = 42
EPOCHS_STAGE1 = 2   # head-only
EPOCHS_STAGE2 = 12  # fine-tune (total 14)
TOTAL_EPOCHS = EPOCHS_STAGE1 + EPOCHS_STAGE2
normal_boost = 2.5  # stronger boost for Normal
time_limit = 1100.0  # seconds (~18.3 min) guard
print("Device:", DEVICE, "Batch:", BATCH_SIZE, "Total epochs:", TOTAL_EPOCHS)

# reproducibility
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
if DEVICE.type=='cuda': torch.cuda.manual_seed_all(SEED)

# ----------------- 4) Dataset helpers & transforms -----------------
class XrayDataset(Dataset):
    def __init__(self, paths, labels, transform):
        self.paths = paths
        self.labels = labels
        self.transform = transform
    def __len__(self):
        return len(self.paths)
    def __getitem__(self, idx):
        img = np.array(Image.open(self.paths[idx]).convert("RGB"))
        x = self.transform(image=img)['image']
        y = torch.tensor(self.labels[idx]).long()
        return x, y

def get_paths(split):
    base = DATA_DIR / split
    paths, labels = [], []
    if not base.exists(): return paths, labels
    for cls, lab in [("NORMAL",0), ("PNEUMONIA",1)]:
        folder = base/cls
        if not folder.exists(): continue
        for f in sorted(folder.glob("*")):
            if f.suffix.lower() in [".jpeg", ".jpg", ".png"]:
                paths.append(str(f))
                labels.append(lab)
    return paths, labels

train_paths, train_labels = get_paths("train")
test_paths, test_labels = get_paths("test")
print("Train:", len(train_paths), "Test:", len(test_paths))

# Strong medical augmentations (Albumentations 1.4 API)
train_tf = A.Compose([
    A.Resize(height=IMG_SIZE, width=IMG_SIZE),

    # High-value medical augmentations
    A.CLAHE(clip_limit=2.0, p=0.40),
    A.RandomBrightnessContrast(brightness_limit=0.25, contrast_limit=0.25, p=0.35),
    A.GaussianBlur(blur_limit=(3,5), p=0.30),
    A.GaussNoise(var_limit=(5.0, 30.0), p=0.25),
    A.Sharpen(alpha=(0.1,0.25), lightness=(0.7,1.0), p=0.25),

    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.12),
    A.Rotate(limit=15, p=0.35),

    # Correct RandomResizedCrop API
    A.RandomResizedCrop(height=IMG_SIZE, width=IMG_SIZE, scale=(0.70, 1.0), ratio=(0.75,1.33), p=0.40),

    A.Normalize(mean=(0.485,0.456,0.406), std=(0.229,0.224,0.225)),
    ToTensorV2()
])

valid_tf = A.Compose([
    A.Resize(height=IMG_SIZE, width=IMG_SIZE),
    A.Normalize(mean=(0.485,0.456,0.406), std=(0.229,0.224,0.225)),
    ToTensorV2()
])

train_ds = XrayDataset(train_paths, train_labels, train_tf)
test_ds = XrayDataset(test_paths, test_labels, valid_tf)

# ----------------- 5) Sampler & loaders -----------------
sample_weights = [normal_boost if l==0 else 1.0 for l in train_labels]
sampler = WeightedRandomSampler(sample_weights, num_samples=len(sample_weights), replacement=True)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, sampler=sampler, num_workers=2, pin_memory=True)
test_loader = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

# Save a few dataset sample images for paper
def save_dataset_samples(out_file=FIG_DIR/"fig1_dataset_samples.png"):
    import random
    samples=[]
    for cls in ["NORMAL","PNEUMONIA"]:
        p = Path(DATA_DIR/"train"/cls)
        if p.exists():
            files = list(p.glob("*"))
            if files:
                samples += random.sample(files, min(2,len(files)))
    if not samples: return
    fig, axs = plt.subplots(1, len(samples), figsize=(4*len(samples),4))
    for ax, fp in zip(axs, samples):
        ax.imshow(Image.open(fp).convert("L"), cmap="gray"); ax.axis("off")
    plt.tight_layout(); plt.savefig(out_file, dpi=200); plt.close()
save_dataset_samples()

# ----------------- 6) Model: Swin-Small -----------------
MODEL_NAME = "swin_small_patch4_window7_224"
model = timm.create_model(MODEL_NAME, pretrained=True, num_classes=2).to(DEVICE)

# Stage1: freeze backbone, train head
for name, p in model.named_parameters():
    p.requires_grad = False
# enable usual head params
for name, p in model.named_parameters():
    if "head" in name or "norm" in name or "fc" in name:
        p.requires_grad = True

# ----------------- 7) Loss, optimizer, scheduler, AMP -----------------
# Loss: try FocalLoss first, else weighted CE
if FocalLoss is not None:
    try:
        criterion = FocalLoss(alpha=[1.8,1.0], gamma=2, reduction="mean")
        print("Using FocalLoss.")
    except Exception as e:
        print("FocalLoss init error:", e)
        criterion = nn.CrossEntropyLoss(weight=torch.tensor([normal_boost,1.0]).to(DEVICE))
else:
    criterion = nn.CrossEntropyLoss(weight=torch.tensor([normal_boost,1.0]).to(DEVICE))
criterion = criterion.to(DEVICE)

optimizer = optim.AdamW(filter(lambda p: p.requires_grad, model.parameters()), lr=1e-3, weight_decay=1e-4)
steps_per_epoch = max(1, math.ceil(len(train_loader)))
# try OneCycle for fast convergence, fallback to None
try:
    scheduler = torch.optim.lr_scheduler.OneCycleLR(optimizer, max_lr=1e-3, steps_per_epoch=steps_per_epoch, epochs=TOTAL_EPOCHS)
except Exception:
    scheduler = None
scaler = torch.cuda.amp.GradScaler(enabled=(DEVICE.type=='cuda'))

# ----------------- 8) Evaluation helper -----------------
def evaluate(model, loader):
    model.eval()
    all_preds, all_probs, all_targs = [], [], []
    loss_sum = 0.0
    with torch.no_grad():
        for imgs, labels in loader:
            imgs = imgs.to(DEVICE); labels = labels.to(DEVICE)
            with torch.cuda.amp.autocast(enabled=(DEVICE.type=='cuda')):
                outs = model(imgs)
                loss = criterion(outs, labels)
            loss_sum += float(loss) * imgs.size(0)
            probs = torch.softmax(outs, dim=1)
            all_probs.extend(probs[:,1].cpu().numpy().tolist())
            all_preds.extend(torch.argmax(probs,1).cpu().numpy().tolist())
            all_targs.extend(labels.cpu().numpy().tolist())
    avg_loss = loss_sum / max(1, len(loader.dataset))
    auc = roc_auc_score(all_targs, all_probs) if len(set(all_targs))>1 else 0.0
    acc = accuracy_score(all_targs, all_preds)
    return avg_loss, acc, auc, all_preds, all_probs, all_targs

# ----------------- 9) Training loop (staged) with time guard -----------------
best_auc = 0.0
history = {"train_loss":[], "val_loss":[], "val_acc":[], "val_auc":[]}
start_time = time.time()

for epoch in range(1, TOTAL_EPOCHS+1):
    model.train()
    running_loss = 0.0
    pbar = tqdm(train_loader, desc=f"Epoch {epoch}/{TOTAL_EPOCHS}")
    for imgs, labels in pbar:
        imgs = imgs.to(DEVICE); labels = labels.to(DEVICE)
        optimizer.zero_grad()
        with torch.cuda.amp.autocast(enabled=(DEVICE.type=='cuda')):
            outs = model(imgs)
            loss = criterion(outs, labels)
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        if scheduler is not None:
            try:
                scheduler.step()
            except Exception:
                pass
        running_loss += float(loss) * imgs.size(0)
        pbar.set_postfix(loss=float(loss))
        # time guard inside loop
        if (time.time() - start_time) > time_limit:
            print("Time limit reached inside batch loop. Breaking.")
            break
    train_loss = running_loss / max(1, len(train_loader.dataset))
    val_loss, val_acc, val_auc, preds, probs, targs = evaluate(model, test_loader)
    history["train_loss"].append(train_loss); history["val_loss"].append(val_loss)
    history["val_acc"].append(val_acc); history["val_auc"].append(val_auc)
    print(f"Epoch {epoch} | TrainLoss {train_loss:.4f} | ValLoss {val_loss:.4f} | ValAcc {val_acc:.4f} | ValAUC {val_auc:.4f}")

    # Save best
    if val_auc > best_auc:
        best_auc = val_auc
        torch.save({
            "model_state": model.state_dict(),
            "optimizer_state": optimizer.state_dict(),
            "epoch": epoch,
            "val_auc": val_auc
        }, "/content/best_swin_small.pth")
        print("Saved /content/best_swin_small.pth")

    # After stage1, unfreeze whole model and switch to lower LR + cosine schedule
    if epoch == EPOCHS_STAGE1:
        print("Unfreezing full model for fine-tuning...")
        for p in model.parameters(): p.requires_grad = True
        optimizer = optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=max(1, TOTAL_EPOCHS - epoch))
        scaler = torch.cuda.amp.GradScaler(enabled=(DEVICE.type=='cuda'))

    # Time guard after epoch
    if (time.time() - start_time) > time_limit:
        print("Time limit reached after epoch. Stopping training.")
        break

print("Training finished. Best val AUC:", best_auc)

# ----------------- 10) Save training curves & figures -----------------
plt.figure(figsize=(8,5))
plt.plot(history["train_loss"], label="train_loss")
plt.plot(history["val_loss"], label="val_loss")
plt.plot(history["val_auc"], label="val_auc")
plt.xlabel("epoch"); plt.legend(); plt.title("Training curves")
plt.savefig(FIG_DIR/"fig_training_curves.png", dpi=300); plt.show()

val_loss, val_acc, val_auc, preds, probs, targs = evaluate(model, test_loader)
print("Final Test Acc:", val_acc, "AUC:", val_auc)
print(classification_report(targs, preds, target_names=["Normal","Pneumonia"]))

cm = confusion_matrix(targs, preds)
plt.figure(figsize=(5,4)); sns.heatmap(cm, annot=True, fmt='d', cmap="Blues"); plt.title("Confusion Matrix"); plt.savefig(FIG_DIR/"fig_confusion.png", dpi=300); plt.show()

if len(probs)>0 and len(set(targs))>1:
    fpr, tpr, _ = roc_curve(targs, probs)
    plt.figure(figsize=(5,4)); plt.plot(fpr,tpr,label=f"AUC={val_auc:.4f}"); plt.xlabel("FPR"); plt.ylabel("TPR"); plt.legend(); plt.title("ROC"); plt.savefig(FIG_DIR/"fig_roc.png", dpi=300); plt.show()

# ----------------- 11) Grad-CAM generation (now grad-cam==1.4.6) -----------------
if ('GradCAM' in globals()) and (GradCAM is not None):
    model.eval()
    # pick a sensible swin target layer with fallbacks
    try:
        target_layer = model.layers[-1].blocks[-1].norm1
    except Exception:
        try:
            target_layer = model.norm
        except Exception:
            target_layer = list(model.children())[-1]
    cam = GradCAM(model=model, target_layers=[target_layer], use_cuda=(DEVICE.type=='cuda'))
    for i in range(min(8, len(test_paths))):
        img_path = test_paths[i]
        raw = np.array(Image.open(img_path).convert("RGB"))/255.0
        inp = valid_tf(image=(raw*255).astype(np.uint8))['image'].unsqueeze(0).to(DEVICE)
        targets_cam = [ClassifierOutputTarget(1)]
        try:
            grayscale_cam = cam(input_tensor=inp, targets=targets_cam)[0]
        except Exception:
            with torch.no_grad(): _ = model(inp)
            grayscale_cam = cam(input_tensor=inp, targets=targets_cam)[0]
        vis = show_cam_on_image(raw, grayscale_cam, use_rgb=True)
        out_file = FIG_DIR / f"fig_gradcam_{i}.png"
        plt.imsave(out_file, vis)
    print("Grad-CAM images saved to", FIG_DIR)
else:
    print("grad-cam not available; skipped Grad-CAM.")

# ----------------- 12) Save final model if none saved -----------------
if not os.path.exists("/content/best_swin_small.pth"):
    torch.save(model.state_dict(), "/content/final_swin_small.pth")
    print("Saved /content/final_swin_small.pth")
else:
    print("Best model available at /content/best_swin_small.pth")

print("Finished. Figures in /content/paper_figures/. Download model from Files pane.")